save manifest to file
gks-anvil/vrs_anvil_toolkit pull request #85
Opened 2024-05-07 08:21 UTC by quinnwai

Addresses
- #83 to save manifest on a non-scattered `vrs_bulk annotate` run to a specific timestamp

2024-05-07 14:07 UTC, bwalsh requested changes
Code looks great.
* needs some tests 
* update readme.
* do we need a short user guide?

2024-05-07 14:07 UTC, bwalsh commented on vrs_anvil/annotator.py
> +    metrics[TOTAL]["timestamp_str"] = timestamp_str
make timestamp_str a constant

2024-05-08 16:06 UTC, quinnwai commented
@bwalsh responding to points...

> * needs some tests

Sounds good. Will work on adding tests for suffix usage, as well as adding tests that didn't exist before including `--scatter` tests and `vrs_bulk ps` tests. 

> * update readme.

Readme is updated a little bit in #87, if you want I could just target 87 to merge into here and add more? Let me know

> * do we need a short user guide?

Similar to above, I can add a commit once that's done so there's no conflicts on the readme?

2024-05-08 17:13 UTC, quinnwai commented on vrs_anvil/annotator.py
> +    metrics[TOTAL]["timestamp_str"] = timestamp_str
updated

2024-05-15 20:11 UTC, quinnwai commented
@bwalsh Updated it to add tests for `ps`, `annotate --scatter`, and doing refactoring of tests to include stubbing out functions, CLI tests, working in a tmp directory.

Ready for your re-review

2024-06-04 05:11 UTC, bwalsh commented
```$ pytest tests/unit/
================================================================================================ test session starts =================================================================================================
platform darwin -- Python 3.12.1, pytest-8.2.1, pluggy-1.5.0
rootdir: /Users/walsbr/anvil/vrs_anvil_toolkit
configfile: pytest.ini
collected 17 items

tests/unit/test_1000g_vcf.py .                                                                                                                                                                                 [  5%]
tests/unit/test_annotator.py ......                                                                                                                                                                            [ 41%]
tests/unit/test_cli.py F....                                                                                                                                                                                   [ 70%]
tests/unit/test_coding_conventions.py .                                                                                                                                                                        [ 76%]
tests/unit/test_collect_vcfs.py .                                                                                                                                                                              [ 82%]
tests/unit/test_metakb.py .                                                                                                                                                                                    [ 88%]
tests/unit/test_translator.py .                                                                                                                                                                                [ 94%]
tests/unit/test_vcf_to_gnomad.py .                                                                                                                                                                             [100%]

====================================================================================================== FAILURES ======================================================================================================
__________________________________________________________________________________________________ test_cli_version __________________________________________________________________________________________________

    def test_cli_version():
        """Test that version can be called and printed"""
        runner = CliRunner()
        result = runner.invoke(cli, "--version")
        expected_strings = ["version"]
        print(result.output)
        for expected_string in expected_strings:
>           assert (
                expected_string in result.output
            ), f"Should have printed {expected_string}"
E           AssertionError: Should have printed version
E           assert 'version' in ''
E            +  where '' = <Result RuntimeError("'vrs_anvil' is not installed. Try passing 'package_name' instead.")>.output

tests/unit/test_cli.py:80: AssertionError
------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------------

============================================================================================== short test summary info ===============================================================================================
FAILED tests/unit/test_cli.py::test_cli_version - AssertionError: Should have printed version```

2024-06-04 19:15 UTC, quinnwai commented
@bwalsh fixed failing --version test and bumped version. Ready for your re-review

2024-07-18 23:25 UTC, bwalsh approved these changes

2024-07-19 17:20 UTC, merged